USE [MSSQLTIPS_DB]
GO

/****** Object:  StoredProcedure [dbo].[SPOTIFY_MOOD_DETECTION]    Script Date: 13-09-2022 22:24:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROC [dbo].[SPOTIFY_MOOD_DETECTION] AS
BEGIN 

/*DELETING DUPLICATE RECORDS*/
WITH ABC AS (
SELECT *,ROW_NUMBER() OVER(PARTITION BY ID ORDER BY ID) AS ROWNUMBER FROM SONGS_FEATURES_DATA
)
DELETE FROM ABC WHERE ROWNUMBER>1

SELECT 
A.SONG_NAME
,A.ARTIST_NAME
,B.[INDEX]
,B.danceability
,B.energy
,B.[key]
,B.loudness
,B.mode
,B.speechiness
,B.acousticness
,B.instrumentalness
FROM dbo.SONGS A 
LEFT JOIN DBO.SONGS_FEATURES_DATA B
ON A.[SONG_ID]=B.[ID]


END
GO


